#!/usr/bin/env python

import sys
import json
import saxypy
import saxypy.utils
from cStringIO import StringIO

def parse_file(file_name):
    handle = open(file_name, 'r')
    data = saxypy.parse(handle)
    handle.close()
    return data

def main():
    if len(sys.argv) == 2:
        data = parse_file(sys.argv[1])
        print saxypy.utils.pretty_format(data)
    elif len(sys.argv) > 2:
        for arg in sys.argv[1:]:
            print '%s %s %s' % ('=' * 30, arg, '=' * 30)
            data = parse_file(arg)
            print saxypy.utils.pretty_format(data)
    else:
        input = StringIO()
        for line in sys.stdin:
            input.write(line)
        input_str = input.getvalue()
        input.close()
        data = saxypy.parse(input_str)
        print saxypy.utils.pretty_format(data)

if __name__ == '__main__':
    main()